export const BINARY = "agentx";
export const DISPLAY = "agentX";
export const PACKAGE = "agentx";
export const GITHUB_REPO = "augustocaruso/agentx";
export const RELEASE_ASSET = "agentx-pack.zip";
export const BOOTSTRAP_TEMP_PREFIX = `${BINARY}-bootstrap`;
export const GENERATED_BY = `GENERATED BY ${DISPLAY}. DO NOT EDIT.`;
export const GENERATED_MARKDOWN_HEADER = `# ${GENERATED_BY}`;
export const GENERATED_COMMENT = `<!-- ${GENERATED_BY} -->`;

export const LEGACY_BINARY = "ogb";
export const LEGACY_PACKAGE = "opencode-gemini-bridge";
export const LEGACY_GITHUB_REPO = "augustocaruso/opencode-gemini-bridge";
export const LEGACY_RELEASE_ASSET = "opencode-gemini-bridge-pack.zip";
export const LEGACY_GENERATED_MARKDOWN_HEADER = "# GENERATED BY OpenCode Gemini Bridge. DO NOT EDIT.";
export const LEGACY_GENERATED_COMMENT = "<!-- GENERATED BY OpenCode Gemini Bridge. DO NOT EDIT. -->";

export function publicBrandText(value: string): string {
  return value
    .replace(/OpenCode Gemini Bridge/g, `${DISPLAY} Bridge`)
    .replace(/ogb-startup-sync/g, `${BINARY}-startup-sync`)
    .replace(/ogb-sidebar/g, `${BINARY}-sidebar`)
    .replace(/\bOGB\b/g, DISPLAY)
    .replace(/\bogb\b/g, BINARY);
}
