#!/usr/bin/env node
/**
 * Minimal GEMINI.md flattener for agentX.
 *
 * Usage:
 *   node expand-gemini.mjs GEMINI.md .opencode/generated/GEMINI.expanded.md
 *
 * Notes:
 * - Expands conservative @file.md imports.
 * - Skips imports inside fenced code blocks.
 * - Detects cycles.
 * - Emits comments for missing imports.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const input = process.argv[2] || 'GEMINI.md';
const output = process.argv[3] || path.join('.opencode', 'generated', 'GEMINI.expanded.md');
const maxDepth = Number(process.env.OGB_MAX_IMPORT_DEPTH || '10');
const seen = new Set();

function resolveImport(raw, baseDir) {
  let p = raw.trim();
  if (p.startsWith('~/') || p.startsWith('~\\')) {
    p = path.join(os.homedir(), p.slice(2));
  }
  if (path.isAbsolute(p)) return path.resolve(p);
  return path.resolve(baseDir, p);
}

function isImportLine(line) {
  // Conservative: only expand lines composed of @path.md tokens.
  // Requires ./, ../, /, ~/, or Windows drive prefix to avoid emails, npm scopes, decorators.
  return /^\s*(@(?:\.{1,2}[\\/]|~[\\/]|[A-Za-z]:[\\/]|\/)[^\s]+\.md\s*)+$/.test(line);
}

function extractImportPaths(line) {
  const re = /@((?:\.{1,2}[\\/]|~[\\/]|[A-Za-z]:[\\/]|\/)[^\s]+\.md)/g;
  const out = [];
  let m;
  while ((m = re.exec(line))) out.push(m[1]);
  return out;
}

function expand(file, depth = 0) {
  const full = path.resolve(file);
  if (depth > maxDepth) return `\n<!-- agentX: max import depth reached at ${full} -->\n`;
  if (seen.has(full)) return `\n<!-- agentX: skipped circular import: ${full} -->\n`;
  if (!fs.existsSync(full)) return `\n<!-- agentX: missing import: ${full} -->\n`;

  seen.add(full);
  const base = path.dirname(full);
  const lines = fs.readFileSync(full, 'utf8').split(/\r?\n/);
  const out = [];
  let inFence = false;

  out.push('', `<!-- agentX BEGIN: ${full} -->`, '');

  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (!inFence && isImportLine(line)) {
      for (const rawPath of extractImportPaths(line)) {
        out.push(expand(resolveImport(rawPath, base), depth + 1));
      }
    } else {
      out.push(line);
    }
  }

  out.push('', `<!-- agentX END: ${full} -->`, '');
  seen.delete(full);
  return out.join('\n');
}

fs.mkdirSync(path.dirname(output), { recursive: true });
const header = [
  '# GENERATED BY agentX. DO NOT EDIT.',
  '',
  `Source: ${path.resolve(input)}`,
  '',
].join('\n');
fs.writeFileSync(output, header + expand(input), 'utf8');
console.log(`Generated ${output}`);
